### ISSUE TITLE
Doesn't return the post list correctly if the content-type header isn't set properly

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/noddity-retrieval#10]
If the content-type is not properly set to something jsony, it looks like fetching the index.json fails.

Found this when running the noddity-butler unit tests with noddity-retrieval 1.5.0.

Still need to write a failing test that specifies different content-type headers.  Also maybe combine the code in http.js/https.js fake-remote-servers?

**Comment by TehShrike** [comment]
Oh and as for the solution - I'm guessing it will probably be "if response.body isn't set, attempt to `JSON.parse(response.text)`).

**Comment by TehShrike** [comment]
It would be an easy fix, I just want to get a failing test in first

**Comment by ArtskydJ** [comment]
In node or the browser?

**Comment by TehShrike** [comment]
In node.  This is the TAP output and stack:

```
TAP version 13
# no server running
# getting all posts with a server error
ok 1 error getting all posts
# getting most recent posts with a server error
ok 2 error getting most recent posts
# getting local posts with a server error
ok 3 error getting local posts
# No file with that name
ok 4 error looking up doesNotExist.lol
# Bad index
/Users/josh/code/noddity-butler/lib/post_manager.js:40
		var fns = arrayOfFileNames.map(function(filename) {
		                           ^
TypeError: arrayOfFileNames.map is not a function
    at getPosts (/Users/josh/code/noddity-butler/lib/post_manager.js:40:30)
    at /Users/josh/code/noddity-butler/lib/index_manager.js:54:5
    at /Users/josh/code/noddity-butler/node_modules/levelup-cache/index.js:87:5
    at /Users/josh/code/noddity-butler/node_modules/levelup-cache/index.js:101:47
    at /Users/josh/code/noddity-butler/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7
    at Immediate._onImmediate (/Users/josh/code/noddity-butler/node_modules/level-mem/node_modules/memdown/memdown.js:125:5)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

The test is here https://github.com/TehShrike/noddity-butler/blob/master/test/errors_should_happen.js#L55

So it looks like it's not valid JSON anyways.  Apparently the issue is that noddity-retrieval should be returning an error object instead of a null array and no error object.

**Comment by TehShrike** [comment]
Cool.  There should probably be another request where the index.json contains invalid content and/or is not found.
