### ISSUE TITLE
Double URL encoding

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/noddity-retrieval#18]
This URL in firefox, requests a file whose filename gets double-encoded: http://kaysercommentary.com/#!/post/Sermons/New%20Testament/Acts/Acts%2028/Acts%2028_26-31.md

Firefox:
![capture](https://cloud.githubusercontent.com/assets/1833684/15490475/f5821d98-212d-11e6-9064-60725620d40e.PNG)

Chrome:
![capture](https://cloud.githubusercontent.com/assets/1833684/15490583/eea606dc-212e-11e6-8215-0b9a3ba09d9b.PNG)

**Comment by TehShrike** [comment]
You had said that this wasn't reproducible any more, right @ArtskydJ?

**Comment by ArtskydJ** [comment]
I was unable to replicate the issue last time I tried, but I'd like to try to replicate it again tonight. (But hopefully not spend much time on it tonight.)

**Comment by ArtskydJ** [comment]
Replicated...

**Comment by TehShrike** [comment]
The specific issue can be tracked at https://github.com/TehShrike/hash-brown-router/issues/5
