### ISSUE TITLE
Improve tests; add real browser testing

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/noddity-retrieval#20]
Right now all the tests just run via node, even the tests of the browserified code.

We need to run *all* of the tests two ways: once from inside a browser using [tape-run](https://github.com/juliangruber/tape-run) or [run-browser](https://github.com/ForbesLindesay/run-browser), and once from node.

Right now each test fires up its own fakeo server and shuts it down at the end.  I think we'll need to break this out into something that starts up the server, triggers tape on all of the files, and then shuts down the server itself.

The browser side will need to fire up a server in some way similar to run-browser's [api usage](https://github.com/ForbesLindesay/run-browser#api-usage) to both serve up the static files and handle the custom responses of the fakeo server if there are any.  (Are there?  Do we just need a static file server anyway?)

**Comment by TehShrike** [comment]
Fixed by https://github.com/TehShrike/noddity-retrieval/commit/97179fcc84ab45cfe6ae9439fe388e702b902a64 and https://github.com/TehShrike/noddity-retrieval/commit/f45bf89b6364c93a09380063947290315a5bc642

**Comment by ArtskydJ** [comment]
What caused the error you ran into on Thursday?

**Comment by TehShrike** [comment]
The server was being shut down before the tests were finished running!  I added [code to node_test.js](https://github.com/TehShrike/noddity-retrieval/blob/master/node_test.js#L23-L31) to watch for tape reporting that the tests were done.
