### ISSUE TITLE
simple-get doesn't seem to play nice with browserify

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/noddity-retrieval#8]
When used in browserify (by building noddity), `item.copy is not a function` gets logged to the console.

**Comment by TehShrike** [comment]
@ArtskydJ ^

**Comment by ArtskydJ** [comment]
Here is a list of solutions: https://github.com/zeke/npm-collection-http-clients

I'll probably try `got` or `super-agent`.

(BTW, do you have replication steps?)

**Comment by TehShrike** [comment]
If noddity-butler is using noddity-retrieval 1.4.0, and you to a real browserify build (not a watchify build), loading Noddity would cause a JS error in Chrome at least

**Comment by ArtskydJ** [comment]
```
C:\Users\Michael\Github\JS_Source>browserify -r got | uglifyjs - | gzip-size | pretty-bytes
60.03 kB

C:\Users\Michael\Github\JS_Source>browserify -r simple-get | uglifyjs - | gzip-size | pretty-bytes
28.41 kB

C:\Users\Michael\Github\JS_Source>browserify -r superagent | uglifyjs - | gzip-size | pretty-bytes
3.67 kB

C:\Users\Michael\Github\JS_Source>browserify -r browser-request | uglifyjs - | gzip-size | pretty-bytes
3.33 kB

C:\Users\Michael\Github\JS_Source>browserify -r xhr | uglifyjs - | gzip-size | pretty-bytes
2.29 kB

```

Looks like the `buffer` polyfill is a bit large.

I think I'll try `superagent`.

**Comment by TehShrike** [comment]
I do like superagent.
